---
- name: Pull docker image of OrganDonation
  hosts: all
  tasks:
    - name: Pull docker image of OrganDonation-angular
      docker_image:
        name: chandan321/organdonation-angular
        source: pull

    - name: Pull docker image of OrganDonation-spring
      docker_image:
        name: chandan321/organdonation-spring
        source: pull